import { Center } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Center>
          <h1>Welcome to Terraria guide 2.0!</h1>
        </Center>
      </main>
    </div>
  );
};

export default Home;
